# [R]eference 
Frequently used collections and functions for the R programming language.

## Collections

### Vector
A vecotr is an ordered collection of objects of the same type

In [1]:
v <- c(0,1)
v

[1] 0 1

In [30]:
v_string <- c("A", "B", "C")
v_string

[1] "A" "B" "C"

In [31]:
s <- seq(from = 0, to = 1, by = 0.1)
s

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [32]:
r <- rep(s, times = 2)
r

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7
[20] 0.8 0.9 1.0

In [33]:
r[c(2,3)] # returns the 2nd and 3rd element of the vector r

[1] 0.1 0.2

### Array
An array is a multi-dimensional collection of objects of the same type

In [43]:
a <- array(1:6, dim = c(2,3)) # matrix of two rows and three columns
a

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

Dimension of an array

In [52]:
dim(m1)

[1] 2 3

Matrix multiplication

In [39]:
m1 <- array(1:6, dim = c(2,3))
m2 <- array(1:6, dim = c(3,2))
m1 %*% m2

[,1] [,2]
[1,] 22   49  
[2,] 28   64

### List
A list is an ordered collection of objects of different types and length.

In [28]:
l <- list("vector" = c(1, 2, 3), "array" = a, "string" = "Hello")
l$array

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

### Data frame
A data frame is a multi-dimensional collection of objects whose columns can be of different types but all of the same length.

In [71]:
d <- data.frame("col1" = c(1,2,3), "col2" = c("one", "two", "three"))
d[, 1] # print the first column

[1] 1 2 3

## Functions

### apply()

In [79]:
apply(m1, MARGIN = 1, FUN = mean) # applies the mean function to each row in the m1 matrix

[1] 3 4

In [76]:
apply(m1, MARGIN = 2, FUN = mean) # applies the mean function to each column in the m1 matrix

[1] 1.5 3.5 5.5

### sample()
It is used to take a sample from a space in which each element has a certain probability to occur. If the "replace" argument is set to TRUE, each element from the space can occur multiple times. For example the space can be made up of two elements, "HEAD" and "TAIL", each with probability 0.5 to occur.  

In [3]:
sample( x = c("HEAD", "TAIL"), prob = c(0.5, 0.5), size = 10, replace = TRUE)

[1] "HEAD" "TAIL" "TAIL" "HEAD" "HEAD" "HEAD" "TAIL" "HEAD" "TAIL" "TAIL"

## Distributions

### Binomial distribution

In [12]:
N <- 3 # number of tosses
k <- 2 # number of successes (e.g. heads)
p <- 0.5 # probability of success at every toss
dbinom(k, size = N, prob = p) 

[1] 0.375